spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://47.94.237.238:3306/my_dev?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456
  rabbitmq:
    host: http://47.94.237.238
    port: 15672
    username: admin
    password: admin
test:
  name: lisi

